eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
foo: foo version 24
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: true
    base-url: http://locahost:9411/
    locator:
      discovery:
        enabled: true
    sender:
      type: WEB
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
